config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#home"

  get "/milkshakes", to: "milkshakes#index", as: "milkshakes"
  post "/milkshakes", to: "milkshakes#create"
  get "/milkshakes/new", to: "milkshakes#new", as: "new_milkshake"
  get "/milkshakes/:id", to: "milkshakes#show", as: "milkshake"
  put "/milkshakes/:id", to: "milkshakes#update"
  patch "/milkshakes/:id", to: "milkshakes#update"
  get "/milkshakes/:id/edit", to: "milkshakes#edit", as: "edit_milkshake"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :ingredients_milkshakes
  has_many :milkshakes, through: :ingredients_milkshakes
  enum kind: { base: 0, flavour: 1, topping: 2 }
  has_one_attached :pic
end

app/models/ingredients_milkshake.rb
class IngredientsMilkshake < ApplicationRecord
  belongs_to :milkshake
  belongs_to :ingredient
end

app/models/milkshake.rb
class Milkshake < ApplicationRecord
  has_many :ingredients_milkshakes
  has_many :ingredients, through: :ingredients_milkshakes
  has_one :image, as: :imageable
  validates :name, :price, presence: true
  validates :price, numericality: { greater_than: 10 }
  has_one_attached :pic
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :milkshakes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/milkshakes_controller.rb
class MilkshakesController < ApplicationController
  before_action :set_milkshake, only: [:show]
  before_action :set_user_milkshake, only: [:edit, :update]
  before_action :authenticate_user!
  
  def index
    if params[:search] && !params[:search].empty?
      @milkshakes = Milkshake.where(name: params[:search])
    else
      @milkshakes = Milkshake.all
    end
  end

  def show
    session = Stripe::Checkout::Session.create(
      payment_method_types: ["card"],
      customer_email: current_user.email,
      line_items: [
        {
          name: @milkshake.name,
          description: @milkshake.description,
          amount: @milkshake.price,
          currency: "aud",
          quantity: 1
        }
      ],
      payment_intent_data: {
        metadata: {
          user_id: current_user.id,
          milkshake_id: @milkshake.id
        }
      },
      success_url: "#{root_url}payment/success?userId=#{current_user.id}&milkshakeId=#{@milkshake.id}",
      cancel_url: "#{root_url}milkshakes/#{@milkshake.id}"
    )

    @session_id = session.id
    @public_key = Rails.application.credentials.dig(:stripe, :public_key)
  end

  def new
    @milkshake = Milkshake.new
    @ingredients = Ingredient.all
  end

  def create
     @milkshake = current_user.milkshakes.create(milkshake_params)

     if @milkshake.errors.any?
      @ingredients = Ingredient.all
      render "new"
     else
      redirect_to milkshake_path(@milkshake)
     end
  end

  def edit
    @ingredients = Ingredient.all
  end

  def update
    if @milkshake.update(milkshake_params)
      redirect_to milkshake_path(params[:id])
    else
      @ingredients = Ingredient.all
      render "edit"
    end
  end

  private

  def milkshake_params
    params.require(:milkshake).permit(:name, :description, :price, :pic, ingredient_ids: [])
  end

  def set_milkshake
    @milkshake = Milkshake.find(params[:id])
  end

  def set_user_milkshake
    @milkshake = current_user.milkshakes.find_by_id(params[:id])

    if @milkshake == nil
      redirect_to milkshakes_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @flavour_count = Ingredient.flavour.count
    @topping_count = Ingredient.topping.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheYard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Login", new_user_session_path %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/milkshakes/_form.html.erb
<% if milkshake.errors.any? %>
  <% milkshake.errors.full_messages.each do |error| %>
    <p>
      <%= error %>
    </p>
  <% end %>
<% end %>

<%= form_with model: milkshake, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :price, "Price (in cents)" %>
    <%= form.number_field :price, min: 0 %>
  </div>
  <div>
    <%= form.label :pic %>
    <%= form.file_field :pic, accept: "image/png,image/gif,image/jpeg,image/jpg" %>
  </div>
  <div>
    <%= form.collection_check_boxes :ingredient_ids, ingredients, :id, :name %>
  </div>
  <%= form.submit %>
<% end %>

app/views/milkshakes/edit.html.erb
<h1>Edit Milkshake</h1>

<%= render 'form', milkshake: @milkshake, ingredients: @ingredients %>

app/views/milkshakes/index.html.erb
<main id="milkshake-index">
  <div class="banner-img"></div>
  <h1>All Milkshakes</h1>
  <form action="<%= milkshakes_path %>" method="GET">
    <input type="search" name="search">
  </form>
  <%= link_to 'Create Milkshake', new_milkshake_path %>
  <section>
    <% @milkshakes.each do |milkshake| %>
      <%= link_to milkshake do %>
      <div>
        <%= image_tag milkshake.pic if milkshake.pic.attached? %>
        <h3><%= milkshake.name %></h3> 
        <p> <%= number_to_currency(milkshake.price / 100.0) %> </p> 
      </div>
      <% end %>
    <% end %>
  </section>
</main>

app/views/milkshakes/new.html.erb
<h1>Create Milkshake</h1>

<%= render 'form', milkshake: @milkshake, ingredients: @ingredients %>

app/views/milkshakes/show.html.erb
<%= @milkshake.to_json %>

<%= link_to "edit", edit_milkshake_path(@milkshake) if current_user.id == @milkshake.user_id %>

<div>
  <button data-stripe="payment">
    Buy <%= number_to_currency(@milkshake.price / 100) %>
  </button>
</div>

<script src="https://js.stripe.com/v3/"></script>

<script>
  document.querySelector("[data-stripe='payment']").addEventListener("click", () => {
    const stripe = Stripe("<%= @public_key %>");
    stripe.redirectToCheckout({
      sessionId: "<%= @session_id %>"
    });
  });
</script>

app/views/pages/home.html.erb
<h1>The Yard</h1>

<div class="hero">

</div>

<p>
  "Damn right it's better than yours"
</p>

<p>
  We have <%= @flavour_count %> flavours and  <%= @topping_count %> toppings!
</p>